org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

kotlin.code.style=official
kotlin.mpp.enableCocoapods=true
kotlin.native.binary.memoryModel=experimental
kotlin.native.useEmbeddableCompilerJar=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
