name = "langbangml-api"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "9cd3a280a54ce2a5b382602f0247b577"

[vars]
PUBLIC_R2_BASE = "https://pub-5a7344c4dab2467eb917ff4b897e066d.r2.dev"
AUDIO_PREFIX = "langbang/audio"
AZURE_SPEECH_REGION = "eastus"

[[d1_databases]]
binding = "DB"
database_name = "langbangml"
database_id = "0c56de2d-285a-4f72-b629-29b508eb8348"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "alpacapps"
