INSERT OR REPLACE INTO ui_labels (locale, label_key, label_value) VALUES
  ('en-US', 'pronunciation.flashcard_quiz', 'Flashcard quiz'),
  ('en-US', 'pronunciation.play', 'Play'),
  ('en-US', 'pronunciation.stop', 'Stop'),
  ('en-US', 'pronunciation.stop_playback', 'Stop playback'),
  ('en-US', 'pronunciation.previous', 'Previous phoneme'),
  ('en-US', 'pronunciation.next', 'Next phoneme'),
  ('en-US', 'pronunciation.common_words', 'Common words'),
  ('en-US', 'pronunciation.tap_mic', 'Tap mic to score yourself'),
  ('en-US', 'pronunciation.offline_mic', 'Offline — mic scoring unavailable'),
  ('en-US', 'pronunciation.listening_say', 'Listening — say'),
  ('en-US', 'pronunciation.opening_mic', 'Opening mic…'),
  ('en-US', 'pronunciation.heard', 'Heard'),
  ('pl-PL', 'pronunciation.flashcard_quiz', 'Quiz fiszek'),
  ('pl-PL', 'pronunciation.play', 'Odtwórz'),
  ('pl-PL', 'pronunciation.stop', 'Stop'),
  ('pl-PL', 'pronunciation.stop_playback', 'Zatrzymaj odtwarzanie'),
  ('pl-PL', 'pronunciation.previous', 'Poprzedni dźwięk'),
  ('pl-PL', 'pronunciation.next', 'Następny dźwięk'),
  ('pl-PL', 'pronunciation.common_words', 'Typowe słowa'),
  ('pl-PL', 'pronunciation.tap_mic', 'Dotknij mikrofonu, aby dostać ocenę'),
  ('pl-PL', 'pronunciation.offline_mic', 'Offline — ocena wymowy niedostępna'),
  ('pl-PL', 'pronunciation.listening_say', 'Słucham — powiedz'),
  ('pl-PL', 'pronunciation.opening_mic', 'Otwieram mikrofon…'),
  ('pl-PL', 'pronunciation.heard', 'Usłyszano');
