-- Beginner-facing Japanese readings. Canonical Japanese text remains in the
-- legacy `pl`, `lemma`, and inflection fields for old clients and audio; this
-- catalog adds an explicit script, kana reading, and Hepburn romaji rendition
-- for every fixed EN→JA starter-pack target.
-- Future EN→JA seed changes must preserve this payload.readings catalog because
-- the mobile clients decode it directly for the shared presentation engine.

UPDATE content_lessons
SET payload_json = json_set(payload_json, '$.readings', json('{"ありがとう":{"japanese":"ありがとう","kana":"ありがとう","romaji":"arigatō"},"いいえ":{"japanese":"いいえ","kana":"いいえ","romaji":"iie"},"すし":{"japanese":"すし","kana":"すし","romaji":"sushi"},"えき":{"japanese":"えき","kana":"えき","romaji":"eki"},"おはよう":{"japanese":"おはよう","kana":"おはよう","romaji":"ohayō"}}')), updated_at = datetime('now')
WHERE content_version_id = 'en-ja-v1' AND lesson_id = 'lesson-01';

UPDATE content_lessons
SET payload_json = json_set(payload_json, '$.readings', json('{"する":{"japanese":"する","kana":"する","romaji":"suru"},"します":{"japanese":"します","kana":"します","romaji":"shimasu"},"行く":{"japanese":"行く","kana":"いく","romaji":"iku"},"行きます":{"japanese":"行きます","kana":"いきます","romaji":"ikimasu"},"来る":{"japanese":"来る","kana":"くる","romaji":"kuru"},"来ます":{"japanese":"来ます","kana":"きます","romaji":"kimasu"},"食べる":{"japanese":"食べる","kana":"たべる","romaji":"taberu"},"食べます":{"japanese":"食べます","kana":"たべます","romaji":"tabemasu"},"飲む":{"japanese":"飲む","kana":"のむ","romaji":"nomu"},"飲みます":{"japanese":"飲みます","kana":"のみます","romaji":"nomimasu"},"見る":{"japanese":"見る","kana":"みる","romaji":"miru"},"見ます":{"japanese":"見ます","kana":"みます","romaji":"mimasu"},"話す":{"japanese":"話す","kana":"はなす","romaji":"hanasu"},"話します":{"japanese":"話します","kana":"はなします","romaji":"hanashimasu"},"聞く":{"japanese":"聞く","kana":"きく","romaji":"kiku"},"聞きます":{"japanese":"聞きます","kana":"ききます","romaji":"kikimasu"},"買う":{"japanese":"買う","kana":"かう","romaji":"kau"},"買います":{"japanese":"買います","kana":"かいます","romaji":"kaimasu"},"分かる":{"japanese":"分かる","kana":"わかる","romaji":"wakaru"},"分かります":{"japanese":"分かります","kana":"わかります","romaji":"wakarimasu"},"私":{"japanese":"私","kana":"わたし","romaji":"watashi"},"私は":{"japanese":"私は","kana":"わたしは","romaji":"watashi wa"},"私を":{"japanese":"私を","kana":"わたしを","romaji":"watashi o"},"私に":{"japanese":"私に","kana":"わたしに","romaji":"watashi ni"},"あなた":{"japanese":"あなた","kana":"あなた","romaji":"anata"},"あなたは":{"japanese":"あなたは","kana":"あなたは","romaji":"anata wa"},"あなたを":{"japanese":"あなたを","kana":"あなたを","romaji":"anata o"},"あなたに":{"japanese":"あなたに","kana":"あなたに","romaji":"anata ni"},"彼":{"japanese":"彼","kana":"かれ","romaji":"kare"},"彼は":{"japanese":"彼は","kana":"かれは","romaji":"kare wa"},"彼を":{"japanese":"彼を","kana":"かれを","romaji":"kare o"},"彼に":{"japanese":"彼に","kana":"かれに","romaji":"kare ni"},"彼女":{"japanese":"彼女","kana":"かのじょ","romaji":"kanojo"},"彼女は":{"japanese":"彼女は","kana":"かのじょは","romaji":"kanojo wa"},"彼女を":{"japanese":"彼女を","kana":"かのじょを","romaji":"kanojo o"},"彼女に":{"japanese":"彼女に","kana":"かのじょに","romaji":"kanojo ni"},"私たち":{"japanese":"私たち","kana":"わたしたち","romaji":"watashitachi"},"私たちは":{"japanese":"私たちは","kana":"わたしたちは","romaji":"watashitachi wa"},"私たちを":{"japanese":"私たちを","kana":"わたしたちを","romaji":"watashitachi o"},"私たちに":{"japanese":"私たちに","kana":"わたしたちに","romaji":"watashitachi ni"},"彼ら":{"japanese":"彼ら","kana":"かれら","romaji":"karera"},"彼らは":{"japanese":"彼らは","kana":"かれらは","romaji":"karera wa"},"彼らを":{"japanese":"彼らを","kana":"かれらを","romaji":"karera o"},"彼らに":{"japanese":"彼らに","kana":"かれらに","romaji":"karera ni"}}')), updated_at = datetime('now')
WHERE content_version_id = 'en-ja-v1' AND lesson_id = 'lesson-02';

UPDATE content_lessons
SET payload_json = json_set(payload_json, '$.readings', json('{"大きい":{"japanese":"大きい","kana":"おおきい","romaji":"ōkii"},"小さい":{"japanese":"小さい","kana":"ちいさい","romaji":"chiisai"},"いい":{"japanese":"いい","kana":"いい","romaji":"ii"},"美しい":{"japanese":"美しい","kana":"うつくしい","romaji":"utsukushii"},"面白い":{"japanese":"面白い","kana":"おもしろい","romaji":"omoshiroi"},"忙しい":{"japanese":"忙しい","kana":"いそがしい","romaji":"isogashii"},"元気":{"japanese":"元気","kana":"げんき","romaji":"genki"},"静か":{"japanese":"静か","kana":"しずか","romaji":"shizuka"},"暑い":{"japanese":"暑い","kana":"あつい","romaji":"atsui"},"寒い":{"japanese":"寒い","kana":"さむい","romaji":"samui"}}')), updated_at = datetime('now')
WHERE content_version_id = 'en-ja-v1' AND lesson_id = 'lesson-03';

UPDATE content_lessons
SET payload_json = json_set(payload_json, '$.readings', json('{"とても":{"japanese":"とても","kana":"とても","romaji":"totemo"},"少し":{"japanese":"少し","kana":"すこし","romaji":"sukoshi"},"今":{"japanese":"今","kana":"いま","romaji":"ima"},"今日":{"japanese":"今日","kana":"きょう","romaji":"kyō"},"明日":{"japanese":"明日","kana":"あした","romaji":"ashita"},"ここ":{"japanese":"ここ","kana":"ここ","romaji":"koko"},"一緒に":{"japanese":"一緒に","kana":"いっしょに","romaji":"issho ni"},"ゆっくり":{"japanese":"ゆっくり","kana":"ゆっくり","romaji":"yukkuri"},"すぐに":{"japanese":"すぐに","kana":"すぐに","romaji":"sugu ni"},"いつも":{"japanese":"いつも","kana":"いつも","romaji":"itsumo"}}')), updated_at = datetime('now')
WHERE content_version_id = 'en-ja-v1' AND lesson_id = 'lesson-04';

UPDATE content_lessons
SET payload_json = json_set(payload_json, '$.readings', json('{"おはようございます。":{"japanese":"おはようございます。","kana":"おはようございます。","romaji":"Ohayō gozaimasu."},"こんにちは。":{"japanese":"こんにちは。","kana":"こんにちは。","romaji":"Konnichiwa."},"こんばんは。":{"japanese":"こんばんは。","kana":"こんばんは。","romaji":"Konbanwa."},"おやすみなさい。":{"japanese":"おやすみなさい。","kana":"おやすみなさい。","romaji":"Oyasuminasai."},"ありがとうございます。":{"japanese":"ありがとうございます。","kana":"ありがとうございます。","romaji":"Arigatō gozaimasu."},"どういたしまして。":{"japanese":"どういたしまして。","kana":"どういたしまして。","romaji":"Dō itashimashite."},"すみません。":{"japanese":"すみません。","kana":"すみません。","romaji":"Sumimasen."},"はじめまして。":{"japanese":"はじめまして。","kana":"はじめまして。","romaji":"Hajimemashite."},"私はアレックスです。":{"japanese":"私はアレックスです。","kana":"わたしはアレックスです。","romaji":"Watashi wa Arekkusu desu."},"お名前は何ですか。":{"japanese":"お名前は何ですか。","kana":"おなまえはなんですか。","romaji":"Onamae wa nan desu ka?"},"よろしくお願いします。":{"japanese":"よろしくお願いします。","kana":"よろしくおねがいします。","romaji":"Yoroshiku onegaishimasu."},"日本語を勉強しています。":{"japanese":"日本語を勉強しています。","kana":"にほんごをべんきょうしています。","romaji":"Nihongo o benkyō shite imasu."},"日本語があまり分かりません。":{"japanese":"日本語があまり分かりません。","kana":"にほんごがあまりわかりません。","romaji":"Nihongo ga amari wakarimasen."},"もう一度言ってください。":{"japanese":"もう一度言ってください。","kana":"もういちどいってください。","romaji":"Mō ichido itte kudasai."},"英語を話せますか。":{"japanese":"英語を話せますか。","kana":"えいごをはなせますか。","romaji":"Eigo o hanasemasu ka?"},"トイレはどこですか。":{"japanese":"トイレはどこですか。","kana":"トイレはどこですか。","romaji":"Toire wa doko desu ka?"},"これはいくらですか。":{"japanese":"これはいくらですか。","kana":"これはいくらですか。","romaji":"Kore wa ikura desu ka?"},"おいしいです。":{"japanese":"おいしいです。","kana":"おいしいです。","romaji":"Oishii desu."},"おすすめはありますか。":{"japanese":"おすすめはありますか。","kana":"おすすめはありますか。","romaji":"Osusume wa arimasu ka?"},"楽しかったです。":{"japanese":"楽しかったです。","kana":"たのしかったです。","romaji":"Tanoshikatta desu."},"いい天気ですね。":{"japanese":"いい天気ですね。","kana":"いいてんきですね。","romaji":"Ii tenki desu ne."},"日本語はまだまだです。":{"japanese":"日本語はまだまだです。","kana":"にほんごはまだまだです。","romaji":"Nihongo wa madamada desu."},"ダイエットは明日からです。":{"japanese":"ダイエットは明日からです。","kana":"ダイエットはあしたからです。","romaji":"Daietto wa ashita kara desu."},"猫の手も借りたいです。":{"japanese":"猫の手も借りたいです。","kana":"ねこのてもかりたいです。","romaji":"Neko no te mo karitai desu."},"お腹と背中がくっつきそうです。":{"japanese":"お腹と背中がくっつきそうです。","kana":"おなかとせなかがくっつきそうです。","romaji":"Onaka to senaka ga kuttsukisō desu."}}')), updated_at = datetime('now')
WHERE content_version_id = 'en-ja-v1' AND lesson_id = 'lesson-05';

UPDATE content_lessons
SET payload_json = json_set(payload_json, '$.readings', json('{"人":{"japanese":"人","kana":"ひと","romaji":"hito"},"友達":{"japanese":"友達","kana":"ともだち","romaji":"tomodachi"},"水":{"japanese":"水","kana":"みず","romaji":"mizu"},"食べ物":{"japanese":"食べ物","kana":"たべもの","romaji":"tabemono"},"家":{"japanese":"家","kana":"いえ","romaji":"ie"},"駅":{"japanese":"駅","kana":"えき","romaji":"eki"},"本":{"japanese":"本","kana":"ほん","romaji":"hon"},"お茶":{"japanese":"お茶","kana":"おちゃ","romaji":"ocha"},"猫":{"japanese":"猫","kana":"ねこ","romaji":"neko"},"日本":{"japanese":"日本","kana":"にほん","romaji":"Nihon"}}')), updated_at = datetime('now')
WHERE content_version_id = 'en-ja-v1' AND lesson_id = 'lesson-06';
